name: Next.js CI/CD Pipeline

on:
  push:
    branches:
      - main 
      - staging  
  pull_request:
    branches:
      - main
      - staging

jobs:
  # 1. Setup Job to check for correct Node and Yarn versions
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.node.outputs.node-version }}
      yarn-version: ${{ steps.yarn.outputs.yarn-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'  

      - name: Cache Yarn Dependencies
        id: yarn
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  # 2. Linting Job
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run ESLint
        run: yarn lint
        env:
          CI: true

  # 3. Testing Job
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Unit Tests
        run: yarn test
        env:
          CI: true

      - name: Run End-to-End Tests
        run: yarn test:e2e
        env:
          CI: true

  # 4. Build Job
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js App
        run: yarn build
        env:
          CI: true

  # 5. Deployment Job 
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build for Deployment
        run: yarn build

     - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image for 'main' branch
      - name: Build and push production image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t andersoninc12/aibosRAG:latest .
          docker push andersoninc12/aibosRAG:latest

      # SSH into VPS and deploy for 'main' branch
      - name: SSH into VPS and deploy for production
        if: github.ref == 'refs/heads/main'
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS (Production)
        if: github.ref == 'refs/heads/main'
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            sudo docker stop aibosRAG || truels -ld 
            sudo docker rm -f aibosRAG || true
            sudo docker rmi andersoninc12/aibosRAG:latest || true
            sudo docker pull andersoninc12/aibosRAG:latest
            sudo docker run  --name epanet -p 8083:3000 andersoninc12/aibosRAG:latest
            EOF